export enum EnvironmentEnums {
  SERVICE_TWILIO_KEY_SID = 'SERVICE_TWILIO_KEY_SID',
  SERVICE_TWILIO_AUTH_TOKEN = 'SERVICE_TWILIO_AUTH_TOKEN',
  SERVICE_TWILIO_ACCOUNT_SID = 'SERVICE_TWILIO_ACCOUNT_SID',
  SERVICE_TWILIO_PHONE = 'SERVICE_TWILIO_PHONE',
}
