version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
