export enum Channel {
  WHATSAPP = 'WHATSAPP',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  GOOGLE_CHAT = 'GOOGLE_CHAT',
}

export enum MessageModel {
  EXPIRED_POE_COUNTER = 'EXPIRED_POE_COUNTER',
  MOVEMENT_ALERT = 'MOVEMENT_ALERT',
  ORGANGE_ALERT_POE = 'ORGANGE_ALERT_POE',
  POE_EXPIRATION_ALERT = 'POE_EXPIRATION_ALERT',
  QUALITY_ALERT_NOTIFICATION = 'QUALITY_ALERT_NOTIFICATION',
  RED_ALERT_POE = 'RED_ALERT_POE',
  SILO_SAT_EXISTENCE_ALERT = 'SILO_SAT_EXISTENCE_ALERT',
  YELLOW_ALERT_POE = 'YELLOW_ALERT_POE',
}

export enum Language {
  ES = 'ES',
  PT = 'PT',
}
